### ISSUE TITLE
Different combinations for different keyboards

### ISSUE THREAD

**Issue by Rajveer86** [iMasanari/cmd-eikana#23]
Would it be possible to implement key remaps specific to certain keyboards?

**Comment by iMasanari** [comment]
Sorry, you can not change the key remapping for each keyboard in the current Eikana.

However, as the High Sierra was announced, Karabiner-elements is not fully supported yet, so we plan to resume development.
I think that it will take time because it will probably be rebuilt from 1, but I would like to correspond with that.

---
ごめんなさい、現在の英かなでは、キーボードごとにキーリマップを変更することはできません。

しかし、High Sierraが発表されたこと、まだKarabiner-elementsが完全対応していないため、開発の再開を予定しています。
おそらく1から作り直すので時間がかかると思いますが、そちらで対応したいと思います。

**Comment by Rajveer86** [comment]
No worries, I was asking as if I could then I could stop using Karabiner-Elements and just use Eikana, but I don't mind using both together.
